### ISSUE TITLE
python error 

### ISSUE THREAD

**Issue by MrMKN** [Joelkb/DQ-the-file-donor#38]
https://github.com/Joelkb/DQ-the-file-donor/commit/587759533a3ffcabfed5d5b82199ee71aabe72b9

python-3.11.1 dos't support  Motor==2.5.1 and new motor version is not support old pymongo 🙁 and new pymongo is not support EvaMaria based umungo Client

**Comment by Joelkb** [comment]
Can you explain more about it on support group?
